name: kungpotato
description: "A new Flutter package project."
version: 0.0.4
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  flutter_gradient_app_bar: ^0.3.1
  icons_plus: ^5.0.0
  scroll_indicator: ^0.0.3
  banner_carousel: ^1.2.1
  flutter_svg: ^2.0.10+1
  reactive_forms: ^17.0.1
  flick_video_player: ^0.9.0
  video_player: ^2.9.1
  reactive_forms_generator: ^5.0.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
