name: kungpotato
description: "A new Flutter package project."
version: 0.0.2
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  flutter_gradient_app_bar: ^0.3.1
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0


flutter:
